/** @file cmake.h
 *  @brief This file contains a definitions interface to CMake.
 */

// Copyright 2015-2017 Leibniz Universitaet Hannover

#ifndef CALQ_CMAKE_H_
#define CALQ_CMAKE_H_

// These header files are generated by CMake
#include "git.h"
#include "timestamp.h"
#include "version.h"

// We compute the build year for convenience
#define CALQ_BUILD_YEAR \
    ( \
        (CALQ_TIMESTAMP_UTC[0] - '0') * 1000 +\
        (CALQ_TIMESTAMP_UTC[1] - '0') *  100 +\
        (CALQ_TIMESTAMP_UTC[2] - '0') *   10 +\
        (CALQ_TIMESTAMP_UTC[3] - '0')\
    )

// This is a list of the defines generated by CMake; uncomment and set these
// to build without CMake
// #define CALQ_TIMESTAMP_UTC "timestamp_utc"
// #define CALQ_BUILD_YEAR 1977
// #define CALQ_GIT_BRANCH "master"
// #define CALQ_GIT_COMMIT_HASH_SHORT "git_commit_hash_short"
// #define CALQ_GIT_COMMIT_HASH_LONG "git_commit_hash_long"
// #define CALQ_VERSION "1.0.0"
// #define CALQ_VERSION_MAJOR 1
// #define CALQ_VERSION_MINOR 0
// #define CALQ_VERSION_PATCH 0

#endif  // CALQ_CMAKE_H_

