/** @file cmake_config.h
 *  @brief This file contains a definitions interface to CMake.
 *  @author Jan Voges (voges)
 *  @bug No known bugs
 */

/*
 *  Changelog
 *  YYYY-MM-DD: What (who)
 */

#ifndef CQ_CMAKE_CONFIG_H
#define CQ_CMAKE_CONFIG_H

// These header files are generated by CMake
#include "git.h"
#include "timestamp.h"
#include "version.h"

// We compute the build year for convenience
#define CQ_BUILD_YEAR \
    ( \
        (CQ_TIMESTAMP_UTC[0] - '0') * 1000 +\
        (CQ_TIMESTAMP_UTC[1] - '0') *  100 +\
        (CQ_TIMESTAMP_UTC[2] - '0') *   10 +\
        (CQ_TIMESTAMP_UTC[3] - '0')\
    )

// This is a list of the defines generated by CMake; uncomment and set these
// to build without CMake
//#define TIMESTAMP_UTC "timestamp_utc"
//#define CQ_BUILD_YEAR 1977
//#define GIT_BRANCH "master"
//#define GIT_COMMIT_HASH_SHORT "git_commit_hash_short"
//#define GIT_COMMIT_HASH_LONG "git_commit_hash_long"
//#define VERSION "1.0.0"
//#define VERSION_MAJOR 1
//#define VERSION_MINOR 0
//#define VERSION_PATCH 0

#endif // CQ_CMAKE_CONFIG_H

