#ifndef CONFIG_H
#define CONFIG_H

// these header files are being generated by CMake
#include "gitrevision.h"
#include "timestamp.h"
#include "version.h"

#define UTCTIMESTAMP _CMAKE_UTCTIME_
#define GITREVISION_LONG _CMAKE_GITREVISION_LONG_
#define GITREVISION_SHORT _CMAKE_GITREVISION_SHORT_
#define BUILD_YEAR \
    ( \
        (UTCTIMESTAMP[ 0] - '0') * 1000 +\
        (UTCTIMESTAMP[ 1] - '0') *  100 +\
        (UTCTIMESTAMP[ 2] - '0') *   10 +\
        (UTCTIMESTAMP[ 3] - '0')\
    )
#define VERSION_MAJOR _CMAKE_VERSION_MAJOR_
#define VERSION_MINOR _CMAKE_VERSION_MINOR_
#define VERSION_PATCH _CMAKE_VERSION_PATCH_

// these #defines can be used when building this program without CMake
//#define UTCTIMESTAMP "utctimestamp"
//#define GITREVISION_LONG "gitrevision_long"
//#define GITREVISION_SHORT "gitrevision_short"
//#define BUILD_YEAR 1977
//#define VERSION_MAJOR 1
//#define VERSION_MINOR 0
//#define VERSION_PATCH 0

#endif // CONFIG_H

